### ISSUE TITLE
Chart title overlapping data on "save as PNG" output

### ISSUE THREAD

**Issue by hangler** [bcgov/workforce-profile-tool#125]
> Chart title is overlaying data on "save as PNG" output

**Comment by karmour** [comment]
Confirmed in Edge.

@stephanieyurchak can you confirm in Chrome?

**Comment by stephanieyurchak** [comment]
The chart title is not overlaying the data, but I do have the Active Filters box being cut off. 
![image](https://user-images.githubusercontent.com/32579391/114639486-d9e0c500-9c82-11eb-9107-4292f6515ef1.png)

**Comment by hangler** [comment]
This should be fixed but now I'm seeing a weird issue in Chrome where the PNG on the Representation tab is failing to generate. Will investigate.

**Comment by karmour** [comment]
Confirming I can't generate a PNG on the Representation tab in Chrome either right now -- other tabs are fine, as are other browsers. 

Also, I still see the labels being cut off on the Comparison and Representation tabs with a long ministry name (see screen shots):
![image](https://user-images.githubusercontent.com/5818030/115067031-315e7b00-9ea5-11eb-8477-112dd0706d10.png)
![image](https://user-images.githubusercontent.com/5818030/115067002-27d51300-9ea5-11eb-951f-a022213ac8b0.png)

**Comment by karmour** [comment]
Removed my last comment because I realized belatedly that my browser had cached the previous deployment, so everything I checked was a day out of date (even downloading to PNG -- crazy!).

The PNG export on the Comparison tab looks good now -- no overlap! I couldn't check the one on the Representation tab -- both Chrome and Edge refused to produce the output.

**Comment by hangler** [comment]
Exporting the image should now work.

**Comment by karmour** [comment]
Looks good to me in Edge. @stephanieyurchak can you confirm in Chrome?

**Comment by stephanieyurchak** [comment]
confirmed in Chrome
